#!/usr/bin/env python3
"""Generate and verify the derived product identifiers (docs/naming.md rule 5).

docs/naming.md is the single source of truth. This tool renders the two artefacts that build and
packaging consume, and in check mode fails when a committed artefact disagrees with the table or
when a retired brand token is still present in the tree. The point is not formatting: it is that
renaming the product must be one table edit plus a test run, and that a half-done rename cannot be
merged.

Usage:
  python3 tools/naming-sync.py check      # CI gate
  python3 tools/naming-sync.py write      # regenerate generated/naming.*
  python3 tools/naming-sync.py get KEY    # one derived value, for scripts
  python3 tools/naming-sync.py self-test  # prove check detects each failure mode
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
NAMING = ROOT / "docs" / "naming.md"
BLOCK_RE = re.compile(r"```yaml\n(.*?)\n```", re.S)
LIST_GROUPS = {"retired_tokens"}
GENERATED = [("naming.env", "generated/naming.env"), ("naming.cmake", "generated/naming.cmake")]
# Groups whose keys are also exposed unprefixed, because scripts ask for "viewer", not "executables.viewer".
FLATTEN = {"brand", "executables", "library", "release"}
CHECK_SUFFIXES = (".md", ".py", ".sh", ".json", ".yml", ".yaml", ".cmake", ".txt", ".in")
# The naming table itself and the superseded ADR must be allowed to mention retired names.
STALE_EXEMPT = ("docs/naming.md", "adr/", "generated/")


def strip_comment(value: str) -> str:
    if "#" in value:
        value = value.split("#", 1)[0]
    return value.strip()


def unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    if value.startswith("[") and value.endswith("]"):
        return ",".join(unquote(p) for p in value[1:-1].split(",") if p.strip())
    return value


def read_table(path: Path = NAMING) -> dict:
    match = BLOCK_RE.search(path.read_text(encoding="utf-8"))
    if not match:
        raise SystemExit("naming-sync: no yaml block found in " + str(path))
    flat = {}
    retired = []
    group = ""
    for raw in match.group(1).splitlines():
        if not raw.strip():
            continue
        line = raw.strip()
        indent = len(raw) - len(raw.lstrip(" "))
        if indent == 0 and line.endswith(":"):
            group = line.rstrip(":")
            continue
        if line.startswith("- "):
            if group in LIST_GROUPS:
                retired.append(unquote(strip_comment(line[2:])))
            continue
        key, sep, rest = line.partition(":")
        if not sep or not rest.strip() or not group:
            continue
        value = unquote(strip_comment(rest))
        flat[group + "." + key.strip()] = value
        if group in FLATTEN:
            flat.setdefault(key.strip(), value)
    flat["retired_tokens"] = retired
    if not flat:
        raise SystemExit("naming-sync: yaml block parsed empty")
    return flat


def render(kind: str, flat: dict) -> str:
    keys = sorted(k for k in flat if "." in k)
    retired = flat.get("retired_tokens", [])
    if kind.endswith(".env"):
        lines = ["# Generated by tools/naming-sync.py from docs/naming.md. Do not edit here.",
                 "# Edit docs/naming.md, then run: python3 tools/naming-sync.py write", ""]
        lines += ["{}={}".format(k.replace(".", "_").upper(), flat[k]) for k in keys]
        lines.append("RETIRED_TOKENS=" + ",".join(retired))
        return "\n".join(lines) + "\n"
    lines = ["# Generated by tools/naming-sync.py from docs/naming.md. Do not edit here.",
             "if(NOT DEFINED TYNYPDF_NAMING_INCLUDED)", "  set(TYNYPDF_NAMING_INCLUDED TRUE)"]
    for k in keys:
        lines.append('  set(TYNYPDF_{} "{}")'.format(k.replace(".", "_").upper(),
                                                     flat[k].replace('"', '\\"')))
    lines += ["  set(TYNYPDF_RETIRED_TOKENS \"{}\")".format(";".join(retired)), "endif()", ""]
    return "\n".join(lines)


def expected(root: Path, flat: dict) -> dict:
    return {root / target: render(target, flat) for _kind, target in GENERATED}


def tracked_files(root: Path) -> list:
    try:
        out = subprocess.run(["git", "-C", str(root), "ls-files"], capture_output=True,
                             text=True, check=True).stdout
        return [root / p for p in out.splitlines() if p]
    except Exception:
        return [p for p in sorted(root.rglob("*")) if p.is_file()
                and ".git/" not in str(p) and "__pycache__" not in str(p)]


def stale_token_hits(root: Path, flat: dict, files: list) -> list:
    hits = []
    for path in files:
        try:
            rel = path.relative_to(root).as_posix()
        except ValueError:
            continue
        if rel.startswith(STALE_EXEMPT) or not rel.endswith(CHECK_SUFFIXES):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for token in flat.get("retired_tokens", []):
            for lineno, line in enumerate(text.splitlines(), 1):
                if re.search(r"\b" + re.escape(token) + r"\b", line):
                    hits.append("{}:{}: retired token {!r}".format(rel, lineno, token))
    return hits


def check(root: Path, flat: dict, files: list = None) -> list:
    problems = []
    for path, want in expected(root, flat).items():
        rel = path.relative_to(root).as_posix()
        if not path.exists():
            problems.append("{}: missing (run: python3 tools/naming-sync.py write)".format(rel))
        elif path.read_text(encoding="utf-8") != want:
            problems.append("{}: differs from docs/naming.md (run naming-sync.py write)".format(rel))
    for token in flat.get("retired_tokens", []):
        if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", token):
            problems.append("docs/naming.md: retired token {!r} is not a word".format(token))
    problems += stale_token_hits(root, flat, files if files is not None else tracked_files(root))
    return problems


def self_test() -> int:
    flat = read_table()
    retired = flat["retired_tokens"]
    if not retired:
        print("FAIL table has no retired_tokens to test against")
        return 1
    token = retired[0]
    cases = []
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        good = expected(root, flat)

        def reset(files):
            for path in root.rglob("*"):
                if path.is_file() and path not in files:
                    path.unlink()
            for path, text in files.items():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")

        def run(files, label, want_problem):
            reset(files)
            problems = check(root, flat)
            ok = (len(problems) > 0) == want_problem
            print("  {} {:<46} {}".format("ok  " if ok else "FAIL", label,
                                          "" if ok else "got " + str(problems)))
            return ok

        cases.append(run(good, "clean tree passes", False))
        env_path = root / GENERATED[0][1]
        cases.append(run({**good, env_path: good[env_path].replace(
            flat["brand.product_name"], "Wrong Name")}, "drifted generated file fails", True))
        cases.append(run({**good, root / "README.md": "Built with the {} engine.\n".format(
            token)}, "retired token in the tree fails", True))
        cases.append(run({k: v for k, v in good.items() if k != root / GENERATED[1][1]},
                         "missing generated file fails", True))
        cases.append(run({**good, root / "docs" / "naming.md":
                          "{} is retired.\n".format(token)},
                         "naming.md is exempt from the token scan", False))
    held = sum(1 for c in cases if c)
    print("naming-sync self-test: {}/{} properties hold".format(held, len(cases)))
    return 1 if held != len(cases) else 0


def main(argv) -> int:
    mode = argv[0] if argv else "check"
    root = ROOT
    for i, a in enumerate(argv):
        if a == "--root":
            root = Path(argv[i + 1])
    flat = read_table(NAMING if root == ROOT else root / "docs" / "naming.md")
    if mode == "self-test":
        return self_test()
    if mode == "get":
        if len(argv) < 2 or argv[1] not in flat:
            print("naming-sync: unknown key (want one of: {})".format(
                ", ".join(sorted(flat)[:6]) + ", ..."), file=sys.stderr)
            return 2
        print(flat[argv[1]])
        return 0
    if mode == "write":
        for path, want in expected(root, flat).items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != want:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(want, encoding="utf-8")
                print("wrote", path.relative_to(root))
            else:
                print("unchanged", path.relative_to(root))
        return 0
    if mode == "check":
        problems = check(root, flat)
        for p in problems:
            print("naming-sync: " + p, file=sys.stderr)
        if problems:
            return 1
        print("naming-sync: OK ({} keys, {} generated files, {} retired tokens guarded)".format(
            len([k for k in flat if "." in k]), len(GENERATED), len(flat.get("retired_tokens", []))))
        return 0
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
